#+auto_tangle: t

* Prologue

This file is the configuration for Emacs on my phone.

The sourceblocks are tangled to ~early-init.el~ and ~init.el~
using [[auto-tangle]].
* early-init.el
:PROPERTIES:
:header-args: :tangle ~/.emacs.d/early-init.el
:END:

** Preamble

#+begin_src emacs-lisp
  ;; early-init.el -*- lexical-binding: t; -*-
  ;; NOTE: early-init.el is generated from config.org.
  ;;       Please edit that file instead.
#+end_src

** Add Termux-Bin to PATH

#+begin_src emacs-lisp
  (when (string-equal system-type "android")
    (let ((termuxpath "/data/data/com.termux/files/usr/bin"))
      (setenv "PATH" (concat (getenv "PATH") ":" termuxpath))
      (setq exec-path (append exec-path (list termuxpath)))))
#+end_src

* init.el
:PROPERTIES:
:header-args: :tangle ~/.emacs.d/init.el
:END:

** Preamble

#+begin_src emacs-lisp
  ;; init.el -*- lexical-binding: t; -*-
  ;; NOTE: init.el is generated from config.org.
  ;;       Please edit that file instead.
#+end_src

** Littering

Write custom variables into seperate file (so we don't touch init.el).

#+begin_src emacs-lisp
  (setq custom-file (concat user-emacs-directory "custom.el"))
  (when (file-exists-p custom-file)
    (load custom-file))
#+end_src

Don't write Lockfiles.

#+begin_src emacs-lisp
  (setq create-lockfiles nil)
#+end_src

Auto-save to the currently visited file.

#+begin_src emacs-lisp
  (auto-save-visited-mode 1)
#+end_src

Write auto-save-files _also_ to temp dir.

#+begin_src emacs-lisp
  (setq auto-save-file-name-transforms
	`((".*" ,temporary-file-directory t)))
#+end_src

Write backups to temp dir.

#+begin_src emacs-lisp
  (setq backup-directory-alist
	`((".*" . ,temporary-file-directory)))
#+end_src

** Packages

#+begin_src emacs-lisp
  ;; Initialize package sources
  (require 'package)

  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("org" . "https://orgmode.org/elpa/")
                           ("elpa" . "https://elpa.gnu.org/packages/")))

  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))

  ;; Initialize use-package on non-Linux platforms
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (require 'use-package)

  (setq use-package-always-ensure t)
#+end_src

** evil

#+begin_src emacs-lisp
  (use-package evil
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    (setq evil-want-C-u-scroll t)
    (setq evil-want-C-i-jump nil)
    :config
    (evil-mode 1)
    (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
    (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)

    ;; Use viual line motions outside of visual-line-mode buffers
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

    (evil-set-initial-state 'messages-buffer-mode 'normal)
    (evil-set-initial-state 'dashboard-mode 'normal))
#+end_src

evil-collection extends evil keybindings.

#+begin_src emacs-lisp
  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init))
#+end_src

Always display the touchscreen keyboard,
even when the buffer is read-only.

#+begin_src emacs-lisp
  (setq touch-screen-display-keyboard t)
#+end_src

Text conversion means that key-presses are not directly
committed to emacs and is necessary for auto-correct etc.
It also breaks chords in evil-normal-state, so its disabled.

#+begin_src emacs-lisp
  (setq overriding-text-conversion-style nil)
#+end_src

** auto-tangle

Tangle source-blocks on save; works together with
~auto_tangle~ option and ~tangle~ ~header-arg~.

#+begin_src emacs-lisp
  (use-package org-auto-tangle
    :hook (org-mode . org-auto-tangle-mode))
#+end_src

** org

sane formatting in src-blocks.

#+begin_src emacs-lisp
  (setq org-src-tab-acts-natively t)
#+end_src

** magit

#+begin_src emacs-lisp
  (use-package magit
    :defer t)
#+end_src

** Completion

Adapted from vertico/README.org

#+begin_src emacs-lisp
  (use-package vertico
    ;; :custom
    ;; (vertico-scroll-margin 0) ;; Different scroll margin
    ;; (vertico-count 20) ;; Show more candidates
    ;; (vertico-resize t) ;; Grow and shrink the Vertico minibuffer
    ;; (vertico-cycle t) ;; Enable cycling for `vertico-next/previous'
    :init
    (vertico-mode))

  ;; Persist history over Emacs restarts. Vertico sorts by history position.
  (use-package savehist
    :init
    (savehist-mode))

  ;; Emacs minibuffer configurations.
  (use-package emacs
    :custom
    ;; Enable context menu. `vertico-multiform-mode' adds a menu in the minibuffer
    ;; to switch display modes.
    (context-menu-mode t)
    ;; Support opening new minibuffers from inside existing minibuffers.
    (enable-recursive-minibuffers t)
    ;; Hide commands in M-x which do not work in the current mode.  Vertico
    ;; commands are hidden in normal buffers. This setting is useful beyond
    ;; Vertico.
    (read-extended-command-predicate #'command-completion-default-include-p)
    ;; Do not allow the cursor in the minibuffer prompt
    (minibuffer-prompt-properties
     '(read-only t cursor-intangible t face minibuffer-prompt)))
#+end_src
