#+auto_tangle: t

* Prologue

This file is the configuration for Emacs on my phone.

The sourceblocks are tangled to ~early-init.el~ and ~init.el~
using [[auto-tangle]].

The actual emacs-app comes from [[./emacs]].

** Doing

* early-init.el
:PROPERTIES:
:header-args: :tangle ~/.emacs.d/early-init.el
:END:

** Preamble

#+begin_src emacs-lisp
  ;; early-init.el -*- lexical-binding: t; -*-
  ;; NOTE: early-init.el is generated from config.org.
  ;;       Please edit that file instead.
#+end_src

** Add Termux-Bin to PATH

#+begin_src emacs-lisp
  (when (string-equal system-type "android")
    (let ((termuxpath "/data/data/com.termux/files/usr/bin"))
      (setenv "PATH" (concat (getenv "PATH") ":" termuxpath))
      (setq exec-path (append exec-path (list termuxpath)))))
#+end_src

* init.el
:PROPERTIES:
:header-args: :tangle ~/.emacs.d/init.el
:END:

** Preamble

#+begin_src emacs-lisp
  ;; init.el -*- lexical-binding: t; -*-
  ;; NOTE: init.el is generated from config.org.
  ;;       Please edit that file instead.
#+end_src

** Littering

Write custom variables into seperate file (so we don't touch init.el).

#+begin_src emacs-lisp
  (setq custom-file (concat user-emacs-directory "custom.el"))
  (when (file-exists-p custom-file)
    (load custom-file))
#+end_src

Don't write Lockfiles.

#+begin_src emacs-lisp
  (setq create-lockfiles nil)
#+end_src

Auto-save to the currently visited file.

#+begin_src emacs-lisp
  (auto-save-visited-mode 1)
#+end_src

Write auto-save-files _also_ to temp dir.

#+begin_src emacs-lisp
  (setq auto-save-file-name-transforms
	`((".*" ,temporary-file-directory t)))
#+end_src

Write backups to temp dir.

#+begin_src emacs-lisp
  (setq backup-directory-alist
	`((".*" . ,temporary-file-directory)))
#+end_src

** Packages

#+begin_src emacs-lisp
  ;; Initialize package sources
  (require 'package)

  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("org" . "https://orgmode.org/elpa/")
                           ("elpa" . "https://elpa.gnu.org/packages/")))

  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))

  ;; Initialize use-package on non-Linux platforms
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (require 'use-package)

  (setq use-package-always-ensure t)
#+end_src

** evil

#+begin_src emacs-lisp
  (use-package evil
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    (setq evil-want-C-u-scroll t)
    (setq evil-want-C-i-jump nil)
    :config
    (evil-mode 1)
    (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
    (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)

    ;; Use viual line motions outside of visual-line-mode buffers
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

    (evil-set-initial-state 'messages-buffer-mode 'normal)
    (evil-set-initial-state 'dashboard-mode 'normal))
#+end_src

evil-collection extends evil keybindings.

#+begin_src emacs-lisp
  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init))
#+end_src

Always display the touchscreen keyboard,
even when the buffer is read-only.

#+begin_src emacs-lisp
  (setq touch-screen-display-keyboard t)
#+end_src

Text conversion means that key-presses are not directly
committed to emacs and is necessary for auto-correct etc.
It also breaks chords in evil-normal-state, so its disabled.

#+begin_src emacs-lisp
  (setq overriding-text-conversion-style nil)
#+end_src

** auto-tangle

Tangle source-blocks on save; works together with
~auto_tangle~ option and ~tangle~ ~header-arg~.

#+begin_src emacs-lisp
  (use-package org-auto-tangle
    :hook (org-mode . org-auto-tangle-mode))
#+end_src

** Synced files

I use the Dropsync app to keep this synced
to my Dropbox.

#+begin_src elisp
  (defvar my/dropbox-dir (file-name-as-directory "/storage/emulated/0/DropsyncFiles"))
#+end_src

** org

Sane formatting in src-blocks.

#+begin_src emacs-lisp
  (setq org-src-tab-acts-natively t)
#+end_src

*** .org.gpg

Installed ~gpg~ on termux, and imported
my key via the commandline there.
Theory: if I did that via emacs I would
not have to set ~GNUPGHOME~.

Need to make emacs ask for the passphrase,
pinentry does not work.

#+begin_src emacs-lisp
  (setenv "GNUPGHOME" "/data/data/com.termux/files/home/.gnupg")
  (setq epg-pinentry-mode 'loopback)
#+end_src

Because of ~epa-file-inhibit-auto-save~,
emacs does not leak plaintext.

*** org-roam

#+begin_src elisp
  (use-package org-roam
  :ensure t
  :init
  (setq org-roam-v2-ack t)
  (setq org-roam-directory
        (file-truename
         (expand-file-name
  	"roam/"
  	my/dropbox-dir)))
  :custom
  (setq org-roam-completion-everywhere t)
  :config
  (org-roam-db-autosync-mode))
#+end_src

** magit

#+begin_src emacs-lisp
  (use-package magit
    :defer t)

  (setq package-install-upgrade-built-in t)
#+end_src

** Completion

Adapted from vertico/README.org

#+begin_src emacs-lisp
  (use-package vertico
    ;; :custom
    ;; (vertico-scroll-margin 0) ;; Different scroll margin
    ;; (vertico-count 20) ;; Show more candidates
    ;; (vertico-resize t) ;; Grow and shrink the Vertico minibuffer
    ;; (vertico-cycle t) ;; Enable cycling for `vertico-next/previous'
    :init
    (vertico-mode))

  ;; Persist history over Emacs restarts. Vertico sorts by history position.
  (use-package savehist
    :init
    (savehist-mode))

  ;; Emacs minibuffer configurations.
  (use-package emacs
    :custom
    ;; Enable context menu. `vertico-multiform-mode' adds a menu in the minibuffer
    ;; to switch display modes.
    (context-menu-mode t)
    ;; Support opening new minibuffers from inside existing minibuffers.
    (enable-recursive-minibuffers t)
    ;; Hide commands in M-x which do not work in the current mode.  Vertico
    ;; commands are hidden in normal buffers. This setting is useful beyond
    ;; Vertico.
    (read-extended-command-predicate #'command-completion-default-include-p)
    ;; Do not allow the cursor in the minibuffer prompt
    (minibuffer-prompt-properties
     '(read-only t cursor-intangible t face minibuffer-prompt)))
#+end_src

From ~orderless~ readme.

#+begin_src emacs-lisp
  (use-package orderless
    :custom
    (completion-styles '(orderless basic))
    (completion-category-overrides '((file (styles partial-completion))))
    (completion-pcm-leading-wildcard t)) ;; Emacs 31: partial-completion behaves like substring
#+end_src

** Keybindings

#+begin_src emacs-lisp
  (use-package general
    :config
    (general-create-definer spc-leader
  			  :states '(normal visual insert emacs)
  			  :keymaps 'override
  			  :prefix "SPC"
  			  :non-normal-prefix "C-SPC")
    (spc-leader
     "w" 'evil-window-map
     "h" 'help-command

     "." 'find-file
     "," 'ibuffer

     "gg" 'magit
     "gb" 'magit-blame

     "s" 'my/open-stuff
     "t" 'my/open-training
     "c" 'my/open-config
     
     "ni"  'org-insert-structure-template
     "no"  'org-open-at-point
     "nrf" 'org-roam-node-find
     "nri" 'org-roam-node-insert
     "nrt" 'org-roam-tag-add
     "nrdd" 'org-roam-dailies-capture-today
     "nrdt" 'org-roam-dailies-capture-tomorrow
     "nrdy" 'org-roam-dailies-capture-yesterday
     "nrdD" 'org-roam-dailies-goto-today
     "nrdT" 'org-roam-dailies-goto-tomorrow
     "nrdc" 'org-roam-dailies-goto-date

     "z" 'save-buffer
     ))
#+end_src

~which-key~ is builtin.

#+begin_src emacs-lisp
  (use-package which-key
  :ensure nil
  :config
  (setq which-key-idle-delay 0.3)
  (which-key-mode 1))
#+end_src

** Phone Keyboard

Make basic editing possible with the
default keyboard.

Esc and tab via volume key.
Note that there's also ~<tab>~, one is ASCII,
the other is console-event, both are used
in emacs (source: claude).
#+begin_src emacs-lisp
  (define-key key-translation-map (kbd "<volume-up>") (kbd "TAB"))
  (define-key key-translation-map (kbd "<volume-down>") (kbd "<escape>"))
#+end_src

Always show the keyboard, also at startup
#+begin_src emacs-lisp
  (setq touch-screen-display-keyboard t)

  (defun my/show-keyboard ()
    "Show the on-screen keyboard."
    (interactive)
    (frame-toggle-on-screen-keyboard (selected-frame) nil))

  (add-hook 'emacs-startup-hook #'my/show-keyboard)
#+end_src

Buttons above the keyboard for modifier keys.
The builtin ~modifier-bar~ is a child of
the toolbar, so we need to enable that for
it to show up.
#+begin_src emacs-lisp
  (tool-bar-mode 1)
  (setq tool-bar-map (make-sparse-keymap))

  (define-key tool-bar-map [dummy]
  	    '(menu-item " " ignore :help "Keep the tool bar visible"))

  (modifier-bar-mode 1)
  (setq tool-bar-button-margin 30)
  (set-frame-parameter nil 'tool-bar-position 'bottom)
#+end_src

Other avenues that I considered, but did
not get to work:
- using the menu-bar and populate it with
  my own buttons, that failed because the
  actual modifying behaviour was too hard
  to implement for ai.
- Using the tool-bar had the same problem,
  plus buttons in the toolbar are icons,
  not text.

** Visual

Clean up a bit

#+begin_src emacs-lisp
  (scroll-bar-mode -1)
  (tooltip-mode -1)
#+end_src

*** Font

Download the ~.ttf~ file to ~/data/data/org.gnu.emacs/files/fonts~,
this is the user font folder on android emacs. I'm using
the variable-font version, but this is guaranteed to work.
I used termux & wget to download.

#+begin_src emacs-lisp
  (set-face-attribute
   'default nil
   :font "Fira Code-17")
#+end_src

*** Theme

#+begin_src emacs-lisp
  (use-package doom-themes
    :config
    (setq
     doom-themes-enable-bold t
     doom-themes-enable-italic t)
    (doom-themes-visual-bell-config)
    (load-theme 'doom-solarized-light t)
    (doom-themes-org-config))
#+end_src

*** Modeline

#+begin_src emacs-lisp
  (use-package all-the-icons)
#+end_src

Make sure to run these and choose
~~/fonts/~ as installation targets.

#+begin_src emacs-lisp :tangle no
  (nerd-icons-install-fonts)
  (all-the-icons-install-fonts)
#+end_src

#+begin_src emacs-lisp
  (use-package doom-modeline
    :config
    (doom-modeline-mode 1))
#+end_src

** Training

#+begin_src emacs-lisp
  (defun my/open-training ()
    "Open training.org in a new buffer."
    (interactive)
    (find-file (expand-file-name "training.org" my/dropbox-dir)))
#+end_src

Cleanly paste yt-links

#+begin_src emacs-lisp
(defun my/paste-clean-link ()
  "Insert clipboard URL at point, stripping query parameters and fragment."
  (interactive)
  (let* ((raw (string-trim (current-kill 0)))
         (clean (replace-regexp-in-string "[?#].*\\'" "" raw)))
    (insert clean)))
#+end_src

** Stuff

#+begin_src emacs-lisp
  (defun my/open-stuff ()
    "Open stuff.org in a new buffer."
    (interactive)
    (find-file (expand-file-name "stuff.org" my/dropbox-dir)))
#+end_src

** Config

Open this file, assuming the repo is at
~~/android-emacs~.

#+begin_src emacs-lisp
  (defun my/open-config ()
    "Open config.org in a new buffer."
    (interactive)
    (find-file "~/android-emacs/config.org"))
#+end_src

** Startup

#+begin_src emacs-lisp
  (setq inhibit-startup-message t)
  (setq initial-buffer-choice (expand-file-name "stuff.org" my/dropbox-dir))
#+end_src

